# Generated by Django 4.2.20 on 2025-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_latitude_donor_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='donorinterest',
            options={'ordering': ['id']},
        ),
    ]
