# Generated by Django 4.2.20 on 2025-04-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("hospital", "Hospital"),
                    ("admin", "Admin"),
                ],
                default="donor",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
