# Generated by Django 4.2.20 on 2025-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
