# Generated by Django 4.2.20 on 2025-04-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0002_bloodrequest_reminder_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="reminder_sent",
        ),
    ]
