# Generated by Django 4.2.20 on 2025-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0003_remove_bloodrequest_reminder_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['id']},
        ),
    ]
