# Generated by Django 4.2.20 on 2025-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
