name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
          run: |
            cat <<EOF > .env
            DB_NAME=testdb
            DB_USER=testuser
            DB_PASSWORD=testpass
            DB_HOST=db
            DB_PORT=5432
            SECRET_KEY=ci-secret-key
            DEBUG=False
            EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker services
        run: docker compose build

      - name: Run migrations & tests
        run: |
          docker compose up -d db
          docker compose run --rm web sh -c "python manage.py wait_for_db && pytest --maxfail=1 --disable-warnings -q"
          docker compose down

      - name: Cleanup
        if: always()
        run: docker compose down -v
